### ISSUE TITLE
Disconnected waterways

### ISSUE THREAD

**Issue by vycius** [govlt/national-basemap#58]
### Steps to reproduce

- https://basemap.startupgov.lt/#16.03/54.712281/24.872145
- https://basemap.startupgov.lt/#15.81/54.969086/25.240639
- https://basemap.startupgov.lt/#15.73/54.930065/25.188754

### Expected behavior

River segments should be connected together.

### Actual behavior

River segments have gaps

### Screenshots

<details open>
<summary>Screenshots demonstration</summary>

<img width="1296" alt="Screenshot 2024-04-19 at 10 27 37" src="https://github.com/govlt/national-basemap/assets/3719141/4e65a47d-e26b-4383-973d-e7112b6196ee">

</details>

**Comment by AndriusGeo** [comment]
These gaps are caused by rivers flowing in culverts in these areas. Right now culverts are not included in basemap river network, mainly because standard style doesn't have symbol for that. But we should definitely fill these gaps and maybe later add to style special symbol for culverts (for example a dashed line).
